# Generated by Django 2.0 on 2020-02-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.DecimalField(decimal_places=0, max_digits=10)),
                ('surname_person', models.CharField(max_length=64)),
                ('name_person', models.CharField(max_length=64)),
                ('patronymic_person', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
                ('address_person', models.CharField(max_length=128)),
                ('address_person_fact', models.CharField(max_length=128)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=9)),
                ('work', models.CharField(default='ТНП', max_length=256)),
                ('vos', models.CharField(max_length=6)),
                ('rank', models.CharField(max_length=24)),
                ('vlk', models.DateField()),
                ('suitability', models.CharField(max_length=24)),
                ('delay', models.DateField()),
                ('team', models.CharField(default='без команди', max_length=64)),
            ],
        ),
    ]
