# Generated by Django 2.0 on 2020-02-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='delay',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='team',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='card',
            name='vlk',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='work',
            field=models.CharField(max_length=256),
        ),
    ]
