# Generated by Django 2.0 on 2020-02-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200207_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='delay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='vlk',
            field=models.DateField(blank=True, null=True),
        ),
    ]
