# Generated by Django 2.0 on 2020-02-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20200213_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
